# generated by datamodel-codegen:
#   filename:  Patient.json
#   timestamp: 2025-12-23T17:48:54+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra, model_serializer, field_validator


class SimpleAttribute(BaseModel):
    class Config:
        extra = Extra.forbid

    value: str | None = None

    # @field_validator('value', mode='before')
    # @classmethod
    # def deserialize_model(cls, input: any) -> str:
    #     return input

    @model_serializer(mode='plain')  
    def serialize_model(self) -> str:  
        return f'{self.value}'


class Coding(BaseModel):
    class Config:
        extra = Extra.forbid

    code: SimpleAttribute | None = None
    display: SimpleAttribute | None = None
    system: SimpleAttribute | None = None


class CodeableConcept(BaseModel):
    class Config:
        extra = Extra.forbid

    text: SimpleAttribute | None = None
    codings: list[Coding] | None = None


class ObservationValue(BaseModel):
    class Config:
        extra = Extra.forbid

    text: SimpleAttribute | None = None
    type: SimpleAttribute | None = None
    number: SimpleAttribute | None = None
    number2: SimpleAttribute | None = None
    codings: list[Coding] | None = None


class RangeValue(BaseModel):
    class Config:
        extra = Extra.forbid

    text: SimpleAttribute | None = None
    lowValue: SimpleAttribute | None = None
    highValue: SimpleAttribute | None = None


class Allergy(BaseModel):
    class Config:
        extra = Extra.forbid

    substance: CodeableConcept | None = None
    category: CodeableConcept | None = None
    reaction: CodeableConcept | None = None
    severity: CodeableConcept | None = None
    effectiveDate: SimpleAttribute | None = None


class ClinicalDocument(BaseModel):
    class Config:
        extra = Extra.forbid

    documentType: CodeableConcept | None = None
    documentTitle: SimpleAttribute | None = None
    effectiveDate: SimpleAttribute | None = None
    documentStatus: CodeableConcept | None = None
    hasAttachment: SimpleAttribute | None = None


class Condition(BaseModel):
    class Config:
        extra = Extra.forbid

    condition: CodeableConcept | None = None
    onsetDate: SimpleAttribute | None = None
    conditionStatus: CodeableConcept | None = None
    resolutionDate: SimpleAttribute | None = None


class Demographics(BaseModel):
    class Config:
        extra = Extra.forbid

    birthDate: SimpleAttribute | None = None
    deceased: CodeableConcept | None = None
    birthSex: CodeableConcept | None = None
    genderIdentity: CodeableConcept | None = None
    race: CodeableConcept | None = None
    ethnicity: CodeableConcept | None = None
    maritalStatus: CodeableConcept | None = None
    primaryLanguage: CodeableConcept | None = None
    deathDate: SimpleAttribute | None = None
    patientIdentifier: SimpleAttribute | None = None


class Encounter(BaseModel):
    class Config:
        extra = Extra.forbid

    encounterIdentifier: SimpleAttribute | None = None
    encounterDiagnosis: CodeableConcept | None = None
    encounterDisposition: SimpleAttribute | None = None
    encounterDateTime: SimpleAttribute | None = None
    encounterEndDateTime: SimpleAttribute | None = None
    encounterLocation: SimpleAttribute | None = None
    encounterType: CodeableConcept | None = None
    encounterReason: CodeableConcept | None = None
    encounterStatus: CodeableConcept | None = None


class Goal(BaseModel):
    class Config:
        extra = Extra.forbid

    goalCategory: CodeableConcept | None = None
    goalPriority: SimpleAttribute | None = None
    goal: CodeableConcept | None = None
    goalStatus: SimpleAttribute | None = None
    startDate: SimpleAttribute | None = None
    effectiveDate: SimpleAttribute | None = None


class HealthAssessment(BaseModel):
    class Config:
        extra = Extra.forbid

    assessment: CodeableConcept | None = None
    resultValue: ObservationValue | None = None
    resultUnit: CodeableConcept | None = None
    effectiveDate: SimpleAttribute | None = None
    issueDateTime: SimpleAttribute | None = None


class Immunization(BaseModel):
    class Config:
        extra = Extra.forbid

    administrationDate: SimpleAttribute | None = None
    immunization: CodeableConcept | None = None
    lotNumber: SimpleAttribute | None = None
    reaction: CodeableConcept | None = None
    expirationDate: SimpleAttribute | None = None
    immunizationStatus: CodeableConcept | None = None


class LabResult(BaseModel):
    class Config:
        extra = Extra.forbid

    order: CodeableConcept | None = None
    test: CodeableConcept | None = None
    resultUnit: CodeableConcept | None = None
    resultValue: ObservationValue | None = None
    interpretation: CodeableConcept | None = None
    specimenType: CodeableConcept | None = None
    resultStatus: CodeableConcept | None = None
    performedDateTime: SimpleAttribute | None = None
    issuedDateTime: SimpleAttribute | None = None
    referenceRange: RangeValue | None = None
    performingSite: CodeableConcept | None = None
    specimenIdentifier: SimpleAttribute | None = None
    specimenSourceSite: CodeableConcept | None = None
    specimenCondition: CodeableConcept | None = None
    specimenCollectionDateTime: SimpleAttribute | None = None
    orderDate: SimpleAttribute | None = None


class MedicalDevice(BaseModel):
    class Config:
        extra = Extra.forbid

    deviceID: CodeableConcept | None = None
    deviceType: CodeableConcept | None = None
    implantationDate: SimpleAttribute | None = None
    deviceStatus: CodeableConcept | None = None


class Medication(BaseModel):
    class Config:
        extra = Extra.forbid

    medication: CodeableConcept | None = None
    doseAmount: SimpleAttribute | None = None
    doseAmountUnit: CodeableConcept | None = None
    doseRoute: CodeableConcept | None = None
    doseQuantity: SimpleAttribute | None = None
    doseQuantityUnit: SimpleAttribute | None = None
    instructions: SimpleAttribute | None = None
    indication: CodeableConcept | None = None
    startDate: SimpleAttribute | None = None
    endDate: SimpleAttribute | None = None
    statementDate: SimpleAttribute | None = None
    adherence: CodeableConcept | None = None
    fillStatus: CodeableConcept | None = None


class Practitioner(BaseModel):
    class Config:
        extra = Extra.forbid

    practitionerName: SimpleAttribute | None = None
    practitionerIdentifier: SimpleAttribute | None = None


class Procedure(BaseModel):
    class Config:
        extra = Extra.forbid

    procedureDateTime: SimpleAttribute | None = None
    procedure: CodeableConcept | None = None
    procedureReason: CodeableConcept | None = None
    procedureStatus: CodeableConcept | None = None
    procedurePerformedDate: SimpleAttribute | None = None


class VitalSign(BaseModel):
    class Config:
        extra = Extra.forbid

    vitalSign: CodeableConcept | None = None
    resultValue: ObservationValue | None = None
    resultUnit: CodeableConcept | None = None
    interpretation: CodeableConcept | None = None
    resultStatus: CodeableConcept | None = None
    performedDateTime: SimpleAttribute | None = None
    performingSite: CodeableConcept | None = None
    referenceRange: RangeValue | None = None
    issuedDateTime: SimpleAttribute | None = None


class Patient(BaseModel):
    allergies: list[Allergy] | None = None
    clinicalDocuments: list[ClinicalDocument] | None = None
    conditions: list[Condition] | None = None
    demographics: Demographics | None = None
    encounters: list[Encounter] | None = None
    goals: list[Goal] | None = None
    healthAssessments: list[HealthAssessment] | None = None
    immunizations: list[Immunization] | None = None
    labResults: list[LabResult] | None = None
    medicalDevices: list[MedicalDevice] | None = None
    medications: list[Medication] | None = None
    practitioners: list[Practitioner] | None = None
    procedures: list[Procedure] | None = None
    vitalSigns: list[VitalSign] | None = None
